[profile.default]
    cache_path     = 'forge-cache'
    evm_version    = "shanghai"
    fs_permissions = [{ access = "read", path = "./out" }]
    libs           = ["lib"]
    optimizer      = true
    optimizer_runs = 20000
    out            = "out"
    src            = "contracts"
    test           = 'test/foundry'

[fmt]
    tab_width = 2
